# Form implementation generated from reading ui file 'calendario.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Calendario(object):
    def setupUi(self, Calendario):
        Calendario.setObjectName("Calendario")
        Calendario.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Calendario.resize(400, 307)
        Calendario.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Calendario)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ventanaCalendario = QtWidgets.QCalendarWidget(parent=Calendario)
        self.ventanaCalendario.setFirstDayOfWeek(QtCore.Qt.DayOfWeek.Monday)
        self.ventanaCalendario.setObjectName("ventanaCalendario")
        self.gridLayout.addWidget(self.ventanaCalendario, 0, 0, 1, 1)

        self.retranslateUi(Calendario)
        QtCore.QMetaObject.connectSlotsByName(Calendario)

    def retranslateUi(self, Calendario):
        _translate = QtCore.QCoreApplication.translate
        Calendario.setWindowTitle(_translate("Calendario", "Fecha de Alta"))
